# Generated by Django 5.0.4 on 2024-05-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='position',
            field=models.TextField(blank=True, default=''),
        ),
    ]
